function createfigure(YMatrix1,mytitle)
%CREATEFIGURE(YMATRIX1)
%  YMATRIX1:  matrix of y data

%  Auto-generated by MATLAB on 31-Jul-2014 15:34:08

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1);
box(axes1,'on');
hold(axes1,'all');

% Create multiple lines using matrix input to plot
plot1 = plot(YMatrix1,'MarkerSize',15);
set(plot1(1),'Marker','hexagram','LineStyle',':','Color',[1 0 1]);
set(plot1(2),'Marker','pentagram','LineStyle','-.',...
    'Color',[0.600000023841858 0.200000002980232 0]);

% Create xlabel
xlabel('Nombre de clicks','LineWidth',10);

% Create ylabel
ylabel('Nombre de pages atteintes','LineWidth',10);

% Create title
title(mytitle,'LineWidth',30,...
    'FontSize',16);
legend('Concertina','Nomao')
