function createfigure(YMatrix1, my_title)
%CREATEFIGURE1(YMATRIX1)
%  YMATRIX1:  matrix of y data

%  Auto-generated by MATLAB on 01-Aug-2014 09:15:33

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1);
box(axes1,'on');
hold(axes1,'all');

% Create multiple lines using matrix input to plot
plot1 = plot(YMatrix1,'Parent',axes1,'MarkerSize',15);
set(plot1(1),'Marker','pentagram','LineStyle',':',...
    'DisplayName','concertina');
set(plot1(2),'Marker','hexagram','LineStyle','--',...
    'DisplayName','redesigned concertina');
set(plot1(3),'Marker','>','LineStyle','-.','DisplayName','nomao');

% Create xlabel
xlabel('Number of clicks','FontSize',14);

% Create ylabel
ylabel('Number of pages reached','FontSize',14);

% Create title
title(my_title,'FontSize',20);

% Create legend
legend1 = legend(axes1,'show');
set(legend1,...
    'Position',[0.570507893400873 0.162955208889694 0.389551391254969 0.199576409253829]);

